### PR TITLE
Fixes HTTP redirect issues when posting a second time

### LINKED ISSUE #89: Getting "Too many HTTP redirects" when attempting to file radars
I'm assuming they made changes at WWDC 2016? Reproduced on two machines with two different developer accounts. It happens on the "Signing in to RadarWeb" step.

screen shot 2016-06-14 at 7 28 32 am

### LINKED ISSUE #91: Unable to post: too many HTTP redirects
Attempting to post a new radar gives the following error message:

screen shot 2016-06-23 at 10 38 06 am

This happens even when none of the cross-posting options actions (copy to clipboard, send to open radar, post to twitter) are selected.

Error occurs on 3 different Mac using both

- OS X 10.11.5
- macOS 10.12 beta 1

### PR DESCRIPTION
**Pull request by matej**
Fixes #91
Fixes #89 (again)

Deletes all rdar cookies before authenticating. Should fix HTTP redirect issues when posting a second rdar without first restarting the app. 

Note that just deleting the "myacinfo" cookie already seems enough to get it working, but decided to purge everthing in case this changes again in the future.

### CODE REVIEW

File: QuickRadar/QRRadarSubmissionService.m [hunk 1]
```diff
@@ -425,6 +425,14 @@ - (void)submitAsyncWithProgressBlock:(void (^)())progressBlock completionBlock:(
 			});
 		}
 
+        // DEBUG: Enable to prevent posting dummy radars if debugging authentication.
+#if 0
+        dispatch_sync(dispatch_get_main_queue(), ^{
+            self.submissionStatusValue = submissionStatusFailed;
+            completionBlock(NO, [NSError errorWithDomain:@"QRDebugDomain" code:0 userInfo:@{NSLocalizedDescriptionKey: @"Manaully canceled in `submitAsyncWithProgressBlock:`!"}]);
```
Comment (guillaume-algis) [inline QuickRadar/QRRadarSubmissionService.m]: s/Manaully/Manually/ 😉

Comment (matej) [inline QuickRadar/QRRadarSubmissionService.m]: Thanks. Fixed.
